version: '3'
services:
  postgres:
    image: 'postgres:latest'      
  redis:
    image: 'redis:latest'
  nginx:
    restart: always   
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'  
    depends_on: 
      - api
      - client
  api:
    depends_on: 
      - postgres
    build:
      dockerfile: Dockerfile.dev
      # tells it to look in the server folder, and this is where it will find that Dockerfile.dev
      context: ./server
    volumes:
      # don't change anything with this directory
      - /app/node_modules
      # for everything else, move to the /app directory (as specified in the server Dockerfile)
      - ./server:/app
    # setup environment variables that will get instantiated at runtime
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    stdin_open: true
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app